In [1]:
import warnings
warnings.filterwarnings("ignore") 
import pandas as pd

In [2]:
dataset = pd.read_csv(r"./data/Polynomial_regression(Position-salary).csv")
dataset.head(4)

            Position  Level  Salary
0   Business Analyst      1   45000
1  Junior Consultant      2   50000
2  Senior Consultant      3   60000
3            Manager      4   80000

In [3]:
dataset = dataset.drop(columns=["Position"])
dataset.head(4)

   Level  Salary
0      1   45000
1      2   50000
2      3   60000
3      4   80000

In [4]:
x = dataset.iloc[:, :-1]
y = dataset["Salary"]

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)

In [15]:
from sklearn.tree import DecisionTreeRegressor

In [42]:
dtr = DecisionTreeRegressor(criterion='squared_error', max_depth=40, splitter="best")
dtr.fit(x_train, y_train)

DecisionTreeRegressor(max_depth=40)

In [43]:
dtr.score(x_train, y_train) * 100, dtr.score(x_test, y_test) * 100

(100.0, 48.611111111111114)

# Hyper Parameter (to get rid of overfitting)

In [51]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

In [52]:
df = {
        "criterion":["squared_error", "friedman_mse", "absolute_error", "poisson"],
        "splitter":["best", "random"],
        "max_depth":[i for i in range(2, 20)]
     }

In [53]:
gd = GridSearchCV(DecisionTreeRegressor(), param_grid=df)
gd.fit(x_train, y_train)

GridSearchCV(estimator=DecisionTreeRegressor(),
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_depth': [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
                                       14, 15, 16, 17, 18, 19],
                         'splitter': ['best', 'random']})

In [54]:
gd.best_params_

{'criterion': 'squared_error', 'max_depth': 2, 'splitter': 'best'}

In [55]:
gd.best_score_

np.float64(nan)

# RandomizedSearchCV

In [58]:
rd = RandomizedSearchCV(DecisionTreeRegressor(), param_distributions=df, n_iter=20)
rd.fit(x_train, y_train)

RandomizedSearchCV(estimator=DecisionTreeRegressor(), n_iter=20,
                   param_distributions={'criterion': ['squared_error',
                                                      'friedman_mse',
                                                      'absolute_error',
                                                      'poisson'],
                                        'max_depth': [2, 3, 4, 5, 6, 7, 8, 9,
                                                      10, 11, 12, 13, 14, 15,
                                                      16, 17, 18, 19],
                                        'splitter': ['best', 'random']})

In [59]:
rd.best_params_

{'splitter': 'random', 'max_depth': 18, 'criterion': 'poisson'}