In [1]:
import pandas as pd

dataset = pd.read_csv(r"/home/satyajit-sahoo/Downloads/bank-loan.csv")
dataset.head(4)

,age,ed,employ,address,income,debtinc,creddebt,othdebt,default,area,married,Gender
0,41,3,17,12,NaN,9.3,11.359392,5.008608,1.0,Urban,No,Female
1,27,1,10,6,31.0,17.3,1.362202,4.000798,0.0,Rural,Yes,Male
2,40,1,15,14,55.0,5.5,0.856075,2.168925,0.0,Urban,Yes,Female
3,41,1,15,14,120.0,2.9,2.658720,0.821280,0.0,NaN,Yes,Male

In [8]:
dataset.isnull().sum()

age           0
ed            0
employ        0
address       0
income        1
debtinc       0
creddebt      0
othdebt       0
default     150
area        847
married       0
Gender        0
dtype: int64

In [28]:
dataset["Gender"] = dataset["Gender"].fillna(dataset["Gender"].mode()[0])

In [29]:
en_data = dataset[["Gender", "married"]]
en_data

     Gender married
0    Female      No
1      Male     Yes
2    Female     Yes
3      Male     Yes
4      Male     Yes
..      ...     ...
845    Male     Yes
846    Male     Yes
847    Male     Yes
848    Male     Yes
849    Male     Yes

[850 rows x 2 columns]

In [34]:
# 1. one hot encoding using get-dummies
# the data's shows as boolean type

pd.get_dummies(en_data).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Gender_Female  850 non-null    bool
 1   Gender_Male    850 non-null    bool
 2   married_No     850 non-null    bool
 3   married_Yes    850 non-null    bool
dtypes: bool(4)
memory usage: 3.4 KB

In [38]:
# 2. to get results in binary type using scikit-learn

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop="first")
ar = ohe.fit_transform(en_data).toarray()

In [39]:
pd.DataFrame(ar,columns=["Gender_Male","married_Yes"])

     Gender_Male  married_Yes
0            0.0          0.0
1            1.0          1.0
2            0.0          1.0
3            1.0          1.0
4            1.0          1.0
..           ...          ...
845          1.0          1.0
846          1.0          1.0
847          1.0          1.0
848          1.0          1.0
849          1.0          1.0

[850 rows x 2 columns]