In [3]:
import pandas as pd
df = pd.DataFrame({"size": ["s", "m", "l", "xl", "s", "m", "l", "s", "s", "l", "xl", "m"]})
df.head(4)

  size
0    s
1    m
2    l
3   xl

In [4]:
ord_data = [["s", "m", "l", "xl"]]

In [5]:
from sklearn.preprocessing import OrdinalEncoder

In [7]:
oe = OrdinalEncoder(categories=ord_data)

In [11]:
oe.fit(df[["size"]])

OrdinalEncoder(categories=[['s', 'm', 'l', 'xl']])

In [13]:
df["en_size"] = oe.transform(df[["size"]])

In [14]:
df

   size  en_size
0     s      0.0
1     m      1.0
2     l      2.0
3    xl      3.0
4     s      0.0
5     m      1.0
6     l      2.0
7     s      0.0
8     s      0.0
9     l      2.0
10   xl      3.0
11    m      1.0

In [ ]:
# encoding using map function

In [18]:
ord_data1 = {"s": 0, "m": 1, "l": 2, "xl": 3}
df["size_en_map"] = df["size"].map(ord_data1)

In [19]:
df

   size  en_size  size_en_map
0     s      0.0            0
1     m      1.0            1
2     l      2.0            2
3    xl      3.0            3
4     s      0.0            0
5     m      1.0            1
6     l      2.0            2
7     s      0.0            0
8     s      0.0            0
9     l      2.0            2
10   xl      3.0            3
11    m      1.0            1

In [ ]:
# on Large data

In [21]:
dataset = pd.read_csv(r"/home/satyajit-sahoo/Downloads/bank-loan.csv")
dataset["area"] = dataset["area"].fillna(dataset["area"].mode()[0])

In [22]:
dataset.head(4)

,age,ed,employ,address,income,debtinc,creddebt,othdebt,default,area,married,Gender
0,41,3,17,12,NaN,9.3,11.359392,5.008608,1.0,Urban,No,Female
1,27,1,10,6,31.0,17.3,1.362202,4.000798,0.0,Rural,Yes,Male
2,40,1,15,14,55.0,5.5,0.856075,2.168925,0.0,Urban,Yes,Female
3,41,1,15,14,120.0,2.9,2.658720,0.821280,0.0,Urban,Yes,Male

In [23]:
en_data_ord = [['Rural', "Urban"]]

In [28]:
from sklearn.preprocessing import OrdinalEncoder

oen = OrdinalEncoder(categories=en_data_ord)

In [33]:
oen

OrdinalEncoder(categories=[['Rural', 'Urban']])

In [31]:
dataset["area"] = oen.fit_transform(dataset[["area"]])

In [32]:
dataset.head(10)

,age,ed,employ,address,income,debtinc,creddebt,othdebt,default,area,married,Gender
0,41,3,17,12,NaN,9.3,11.359392,5.008608,1.0,1.0,No,Female
1,27,1,10,6,31.0,17.3,1.362202,4.000798,0.0,0.0,Yes,Male
2,40,1,15,14,55.0,5.5,0.856075,2.168925,0.0,1.0,Yes,Female
3,41,1,15,14,120.0,2.9,2.658720,0.821280,0.0,1.0,Yes,Male
4,24,2,2,0,28.0,17.3,1.787436,3.056564,1.0,1.0,Yes,Male
5,41,2,5,5,25.0,10.2,0.392700,2.157300,0.0,1.0,Yes,Male
6,39,1,20,9,67.0,30.6,3.833874,16.668126,0.0,1.0,No,Male
7,43,1,12,11,38.0,3.6,0.128592,1.239408,0.0,1.0,NaN,Female
8,24,1,3,4,19.0,24.4,1.358348,3.277652,1.0,1.0,NaN,Male
9,36,1,0,13,25.0,19.7,2.777700,2.147300,0.0,1.0,NaN,NaN